"""
GlassBox Agent — Reviewer
============================

CORE AGENT. Requires owner approval to modify.

Purpose:
    Adversarial review of work done by other agents. The reviewer's job is to find
    problems that the fix-generating agent missed.

Why this is a CORE agent:
    The reviewer is the trust mechanism. Without it, the system would blindly ship
    whatever the fix generator produces. The reviewer provides the "second opinion"
    that makes GlassBox trustworthy.

Why a DIFFERENT model:
    This agent MUST use a different LLM model than the agent that produced the work.
    Same model = same blind spots. If GPT-4o generates a fix, GPT-4o reviewing it
    will likely miss the same edge cases it missed while generating.

    Our failure analysis (Issues #18, #19) confirmed this:
        "100% failure on cross-boundary. Debate approves broken fixes."
    The debate was using the same model for all agents. Different models catch
    different errors.

    Default: Claude 3.5 Sonnet for review when GPT-4o generates fixes.

How it works:
    1. Receives the diff (what changed), test results, and original issue via ctx.config.
    2. Calls a DIFFERENT LLM model with a review prompt.
    3. Returns approved/rejected with specific concerns.

    If rejected, the engine routes back to the fix generator with the reviewer's
    feedback, so it can address the concerns on the next attempt.
"""

from __future__ import annotations

from typing import Any

from glassbox.core.models import AgentContext
from glassbox.tools.llm import call_llm


# ---------------------------------------------------------------------------
# The review prompt.
#
# This prompt asks the reviewer to be CRITICAL, not helpful.
# The fix generator is helpful — it tries to solve the problem.
# The reviewer is skeptical — it tries to find what's wrong with the solution.
#
# The prompt explicitly asks for:
#   - Edge cases the fix doesn't handle
#   - Regressions the fix might introduce
#   - Whether the fix actually addresses the issue
#   - Whether the diff is minimal (no unnecessary changes)
# ---------------------------------------------------------------------------

REVIEW_PROMPT = """You are the GlassBox Reviewer. Your job is to find problems.

You are reviewing a code fix generated by another AI agent. Be CRITICAL.
The other agent used {gen_model}. You are {review_model}. Different perspectives matter.

Original issue #{issue_number}: {title}
{body}

Diff (what was changed):
{diff}

Test results:
{test_results}

REVIEW CRITERIA:
1. Does this fix actually address the issue described?
2. Are there edge cases the fix doesn't handle?
3. Could this fix introduce regressions in other parts of the code?
4. Is the diff minimal? (No unnecessary changes, no refactoring, no added comments)
5. Do the tests actually verify the fix, or are they superficial?

Return ONLY valid JSON:
{{
  "approved": true,
  "concerns": ["List of specific concerns, empty if approved"],
  "suggestion": "If rejected, what should be changed. Empty if approved."
}}"""


def run(ctx: AgentContext, **kwargs: Any) -> dict[str, Any]:
    """
    Review a fix produced by another agent. Returns approved/rejected.

    This is the agent entry point called by the engine.

    Reads from ctx.config:
        title          → Issue title
        body           → Issue body
        diff           → The code diff to review (str)
        test_results   → Test results summary (str)
        gen_model      → Model that generated the fix (e.g., "gpt-4o")
        review_model   → Model to use for review (default: "claude-3-5-sonnet-20241022")
        temperature    → LLM temperature (default: 0.3 for deterministic review)

    Returns:
        {"event": "approved" or "rejected", "detail": str, "concerns": list[str]}
    """

    title = ctx.config.get("title", "")
    body = ctx.config.get("body", "")
    diff = ctx.config.get("diff", "(no diff available)")
    test_results = ctx.config.get("test_results", "(no test results)")
    gen_model = ctx.config.get("model", "gpt-4o")
    review_model = ctx.config.get("review_model", "claude-3-5-sonnet-20241022")
    temperature = ctx.config.get("temperature_review", 0.3)

    # Build the review prompt with all context.
    prompt = REVIEW_PROMPT.format(
        issue_number=ctx.issue_number,
        title=title,
        body=body,
        diff=diff,
        test_results=test_results,
        gen_model=gen_model,
        review_model=review_model,
    )

    # Call a DIFFERENT model than the one that generated the fix.
    # This is the key trust mechanism: model diversity catches different errors.
    raw_response = call_llm(
        model=review_model,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature,
        json_mode=True,
    )

    # Parse the response.
    import json
    try:
        data = json.loads(raw_response.strip().strip("`").lstrip("json").strip())
    except json.JSONDecodeError:
        # If we can't parse the review, reject as a safety measure.
        # Better to re-review than to ship an unreviewed fix.
        return {
            "event": "rejected",
            "detail": f"Failed to parse reviewer response: {raw_response[:200]}",
            "concerns": ["Review response was unparseable — needs re-review"],
        }

    approved = data.get("approved", False)
    concerns = data.get("concerns", [])
    suggestion = data.get("suggestion", "")

    return {
        "event": "approved" if approved else "rejected",
        "detail": suggestion if not approved else "Fix approved by reviewer.",
        "concerns": concerns,
    }
